version: "3"
services:

  api:
    build: 
      context: ./microservices

  redis:
    image: 'redis'

  cache-proxy:
    depends_on:
      - redis
    build: 
      context: ../src
    ports:
      - "5000:5000"
    environment:
      - SERVING_HOST=0.0.0.0
      - SERVING_PORT=5000
      - TARGET_LOCATION=api:5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  request-router:
    depends_on:
      - cache-proxy
    build:
      context: ./nginx
    ports:
      - "8080:80"




