version: "3"
services:

  microservice:
    build: 
      context: ./microservices

  redis-cache:
    image: 'redis'

  caching-proxy:
    depends_on:
      - redis-cache
    build: 
      context: ../src
    ports:
      - "5000:5000"
    environment:
      - SERVING_HOST=0.0.0.0
      - SERVING_PORT=5000
      - TARGET_LOCATION=microservice:5000
      - REDIS_HOST=redis-cache
      - REDIS_PORT=6379

  request-router:
    depends_on:
      - caching-proxy
    build:
      context: ./nginx
    ports:
      - "8080:80"




