version: "3"
services:

  api:
    build: 
      context: ./test/cached_service

  redis:
    image: 'redis'

  cache-proxy:
    depends_on:
      - redis
    build: 
      context: ./src
    ports:
      - "5000:5000"
    environment:
      - SERVING_PORT=5000
      - RECEIVE_FROM=cache
      - REDIRECT_TO=api:5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  request-router:
    depends_on:
      - cache-proxy
    build:
      context: ./test/nginx
    ports:
      - "8080:80"




